### ISSUE TITLE
The project does not contain full history 

### ISSUE THREAD

**Issue by hmansari** [SoftwareEngineeringToolDemos/ICSE-2011-AutoBlackTest#2]
I could not find the full history of the project . Could you please clarify ? Thanks.

**Comment by srvxid** [comment]
The project source code was hosted in author's [website](http://www.lta.disco.unimib.it/tools/AutoBlackTest/AutoBlackTest/Home.html) and not in any Git or SVN repository which could have been forked. Hence, this is the first time the code is put on GitHub and there is no history of the project.
